openapi: 3.0.0
info:
  contact: {}
  title: ainori_delivery_company_v1.0
  version: '1.0'
  description: delivery company
servers:
  - url: 'http://localhost:3000'
paths:
  /companies:
    parameters: []
    get:
      summary: Get postage fee
      tags: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/company'
              examples:
                Get postage fee.:
                  value:
                    fee: 100
            application/xml:
              schema:
                $ref: '#/components/schemas/fee'
        '400':
          description: Bad Request
        '':
          headers: {}
      description: Retrieve the fees of the postage.
      operationId: ''
    delete:
      summary: ''
      operationId: ''
      responses:
        '200':
          description: OK
        '404':
          description: Not detected. The resource with postage was not found.
      description: Delete the postage specified in the path
  /postage:
    post:
      summary: Create New User
      operationId: ''
      responses:
        '200':
          description: Created new postage
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  fbaID:
                    type: string
                    minLength: 1
                  boxID:
                    type: integer
                  fee:
                    type: integer
                required:
                  - fbaID
                  - boxID
                  - fee
              examples:
                New postage Fellow:
                  value:
                    fbaID: NRT1
                    boxID: 40
                    fee: 500
            application/xml:
              schema:
                type: object
                properties: {}
        '409':
          description: Conflict. The request cannot be completed because combination of fbaID and boxID conflicts with the current resource.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                fbaID:
                  type: string
                  minLength: 1
                boxID:
                  type: number
                fee:
                  type: number
              required:
                - fbaID
                - boxID
                - fee
            examples:
              Add new postage:
                value:
                  fbaID: NRT1
                  boxID: 40
                  fee: 500
        description: Post the necessary fields for the API to create a new postage.
      description: Create postage fee.
    parameters: []
    put:
      summary: ''
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  fbaID:
                    type: string
                    minLength: 1
                  boxID:
                    type: integer
                  fee:
                    type: integer
                required:
                  - fbaID
                  - boxID
                  - fee
              examples:
                update of existing postage:
                  value:
                    fbaID: NRT1
                    boxID: 60
                    fee: 800
        '404':
          description: Not detected. The resource with combination of fbaID and boxID was not found.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                fbaID:
                  type: string
                  minLength: 1
                boxID:
                  type: integer
                fee:
                  type: integer
              required:
                - fbaID
                - boxID
                - fee
            examples:
              Update of existing postage:
                value:
                  fbaID: NRT1
                  boxID: 60
                  fee: 800
        description: Update of existing postage
      description: Update of existing postage.
components:
  schemas:
    company:
      type: object
      title: ''
      x-examples: {}
      description: delivery company
      properties:
        id:
          type: integer
          description: '600'
          format: int64
        companyName:
          type: string
