openapi: 3.0.0
info:
  title: atw-invoice-system-packing-fee
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /materials:
    parameters: []
    get:
      summary: Get fees of packing material
      tags: []
      responses:
        '200':
          description: Materials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'
              examples:
                Get materials:
                  value:
                    - materialID: 1
                      materialName: material-A
                      fee: 100
                    - materialID: 2
                      materialName: material-B
                      fee: 200
                    - materialID: 3
                      materialName: material-C
                      fee: 300
                    - materialID: 4
                      materialName: material-D
                      fee: 400
                    - materialID: 5
                      materialName: material-E
                      fee: 500
        '400':
          description: Bad Request
      operationId: get-material-fee
      description: Retrieve the fees of the packing materials.
  '/material/{materialName}/{fee}/{materialID}':
    post:
      summary: Create New User
      operationId: post-material-fee
      responses:
        '200':
          description: packing material fee Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'
              examples:
                New Packing material fee Fellow:
                  value:
                    materialID: 6
                    materialName: material-F
                    fee: 600
        '400':
          description: Missing Required Information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                materialID:
                  type: integer
                  description: material ID
                materialName:
                  type: string
                  description: material Name
                fee:
                  type: integer
                  description: fee
              required:
                - materialID
                - materialName
                - fee
            examples:
              Create material:
                value:
                  materialName: material-F
                  fee: 600
        description: Post the necessary fields for the API to create a new user.
      description: Create packing material fee.
    patch:
      summary: ''
      operationId: patch-material
      responses:
        '200':
          description: |-
            {
              "materialID": 6,
              "materialName": "material-F",
              "fee": 600
            }
    parameters:
      - schema:
          type: integer
        name: materialID
        in: path
        description: material name
        required: true
      - schema:
          type: string
        name: materialName
        in: path
        required: true
        description: material fee
      - schema:
          type: integer
        name: fee
        in: path
        required: true
components:
  schemas:
    Material:
      title: Material
      type: object
      description: packing material fee
      x-examples:
        materials:
          - materialID: 1
            materialName: material-A
            fee: 100
          - materialID: 2
            materialName: material-B
            fee: 200
          - materialID: 3
            materialName: material-C
            fee: 300
          - materialID: 4
            materialName: material-D
            fee: 400
          - materialID: 5
            materialName: material-E
            fee: 500
      properties:
        materialID:
          type: integer
          description: '1'
        materialName:
          type: string
          description: material-A
        fee:
          type: integer
          description: '100'
      required:
        - materialID
        - materialName
        - fee
