openapi: 3.0.0
info:
  title: atw-invoice-system-packing-fee
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /materials:
    parameters: []
    get:
      summary: Get fees of packing material
      tags: []
      responses:
        '200':
          description: Materials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'
              examples:
                Get materials:
                  value:
                    material-A: 100
                    material-B: 200
                    material-C: 300
                    material-D: 400
                    material-E: 500
        '400':
          description: Bad Request
      operationId: get-material-fee
      description: Retrieve the fees of the packing materials.
  '/material/{materialName}/{fee}':
    post:
      summary: Create New User
      operationId: post-material-fee
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'
              examples:
                New Packing material fee Fellow:
                  value:
                    materialName: material-F
                    fee: 600
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                materialName:
                  type: string
                  description: material name
                fee:
                  type: integer
                  description: fee
              required:
                - materialName
                - fee
            examples:
              Create material:
                value:
                  materialName: material-F
                  fee: 600
        description: Post the necessary fields for the API to create a new user.
      description: Create packing material fee.
    patch:
      summary: ''
      operationId: patch-material
      responses:
        '200':
          description: OK
    parameters:
      - schema:
          type: string
        name: materialName
        in: path
        description: material name
        required: true
      - schema:
          type: integer
        name: fee
        in: path
        required: true
        description: material fee
components:
  schemas:
    Material:
      title: Materials
      type: object
      description: ''
      x-examples:
        materials:
          material-A: 100
          material-B: 200
          material-C: 300
          material-D: 400
          material-E: 500
      properties:
        materialName:
          type: string
          description: 100 yen
        fee:
          type: integer
          description: 200 yen
      required:
        - materialName
        - fee
