openapi: 3.0.0
info:
  title: atw-invoice-system-packing-fee
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /materials:
    parameters: []
    get:
      summary: Get fees of packing material
      tags: []
      responses:
        '200':
          description: Materials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'
              examples:
                Get materials:
                  value:
                    material-A: 100
                    material-B: 200
                    material-C: 300
                    material-D: 400
                    material-E: 500
        '400':
          description: Bad Request
      operationId: get-material-fee
      description: Retrieve the fees of the packing materials.
  /material:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                materialName:
                  type: string
                  description: material name
                fee:
                  type: integer
                  description: fee
              required:
                - materialName
                - fee
            examples:
              Create material:
                value:
                  materialName: material-F
                  fee: '600'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  '/material/{materialID}':
    parameters: []
    patch:
      summary: ''
      operationId: patch-material-materialID
      responses:
        '200':
          description: OK
components:
  schemas:
    Material:
      title: Materials
      type: object
      description: ''
      x-examples:
        materials:
          material-A: 100
          material-B: 200
          material-C: 300
          material-D: 400
          material-E: 500
      properties:
        material-A:
          type: integer
          description: 100 yen
        material-B:
          type: integer
          description: 200 yen
        material-C:
          type: integer
          description: 300 yen
        material-D:
          type: integer
          description: 400 yen
        material-E:
          type: integer
          description: 500 yen
      required:
        - material-A
        - material-B
        - material-C
        - material-D
        - material-E
