openapi: 3.0.0
info:
  title: atw-invoice-system-packing-fee
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /materials:
    parameters: []
    get:
      summary: Get fees of packing material
      tags: []
      responses:
        '200':
          description: Fees for packing materials received in response
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  materialID:
                    type: number
                  materialName:
                    type: string
                    minLength: 1
                  fee:
                    type: number
                required:
                  - materialID
                  - materialName
                  - fee
              examples:
                Get packing material fee.:
                  value:
                    materialID: 1
                    materialName: material-A
                    fee: 100
        '400':
          description: Bad Request
      description: Retrieve the fees of the packing materials.
      operationId: ''
  /material:
    post:
      summary: Create New User
      operationId: ''
      responses:
        '200':
          description: packing material fee Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'
              examples:
                New Packing material fee Fellow:
                  value:
                    materialID: 6
                    materialName: material-F
                    fee: 600
            application/xml:
              schema:
                type: object
                properties: {}
        '400':
          description: Missing Required Information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                materialID:
                  type: number
                  description: material ID
                materialName:
                  type: string
                  description: material Name
                fee:
                  type: number
                  description: fee
              required:
                - materialID
                - materialName
                - fee
            examples:
              Create material:
                value:
                  materialID: 6
                  materialName: material-F
                  fee: 600
        description: Post the necessary fields for the API to create a new user.
      description: Create packing material fee.
    patch:
      summary: ''
      operationId: ''
      responses:
        '200':
          description: |-
            {
              "materialID": 6,
              "materialName": "material-F",
              "fee": 600
            }
      description: update of existing packaging material or fee
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                materialID:
                  type: number
                materialName:
                  type: string
                  minLength: 1
                fee:
                  type: number
              required:
                - materialID
                - materialName
                - fee
            examples:
              Add material-F:
                value:
                  materialID: 6
                  materialName: material-F
                  fee: 600
    parameters: []
components:
  schemas:
    Material:
      title: Material
      type: object
      description: packing material fee
      x-examples:
        packing material fee:
          materialID: 1
          materialName: material-A
          fee: 100
      properties:
        materialID:
          type: number
          description: '1'
        materialName:
          type: string
          description: material-A
        fee:
          type: number
          description: '100'
      required:
        - materialID
        - materialName
        - fee
