swagger: '2.0'
info:
  description: Delivery companies that delivers to the Japan warehouse.
  version: 1.0.0
  title: Delivery company
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:3000'
basePath: /v1
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
schemes:
  - https
paths:
  /companies:
    post:
      tags:
        - pet
      summary: Add delivery company
      description: Add delivery company. Only admin can run.
      operationId: ''
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Delivery company object.
          required: true
          schema:
            $ref: '#/definitions/Company'
      responses:
        '201':
          description: Resource add completed successfully
          schema:
            type: object
            properties: {}
        '400':
          description: Request is invalid or parameters are incorrect
          schema:
            type: object
            properties: {}
        '409':
          description: Tried to register an ID that already exists
          schema:
            type: object
            properties: {}
    put:
      tags:
        - pet
      summary: Update delivery company
      description: Update delivery company. Only admin can run.
      operationId: ''
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Company'
          description: Delivery company object.
      responses:
        '201':
          description: Resource update completed successfully
          schema:
            type: object
            properties: {}
        '400':
          description: Request is invalid or parameters are incorrect
          schema:
            type: object
            properties: {}
        '404':
          description: Requested resource does not exist
          schema:
            type: object
            properties: {}
    parameters: []
  '/company/{companyId}':
    get:
      tags:
        - store
      summary: Get delivery company
      description: Get delivery company.
      operationId: ''
      produces:
        - application/xml
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ID of pet that needs to be fetched
          required: true
          type: integer
          maximum: 10
          minimum: 1
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Company'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
    delete:
      tags:
        - store
      summary: Delete delivery company
      description: Delete delivery company. Only admin can run.
      operationId: ''
      produces:
        - application/xml
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ID of the order that needs to be deleted
          required: true
          type: integer
          minimum: 1
          format: int64
      responses:
        '204':
          description: Deleted the delivery company
          schema:
            type: object
            properties: {}
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
    parameters:
      - type: string
        name: companyId
        in: path
        required: true
securityDefinitions: {}
definitions:
  Company:
    title: Company
    type: object
    properties:
      id:
        type: integer
      companyName:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
